apiVersion: apps/v1
kind: Deployment
metadata:
  name: globomantics-ui  
spec:
  selector:
    matchLabels:
      app: globomantics-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: globomantics-ui
    spec:
      containers:
      - name: ui
        image: 073431393079.dkr.ecr.us-west-2.amazonaws.com/globomantics_ui:latest        
        envFrom:
          - configMapRef:
              name: globo-ui-config
          - secretRef:
              name: globoconn-secrets 
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5000"        

---
apiVersion: v1
kind: Service
metadata:
  name: globoui-service
spec:
  selector:
    app: globomantics-ui  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 5000
      targetPort: 5000      